---
title: "R Notebook"
output: html_notebook
---
```{r}
library(Seurat)
```


```{r}
C4 <- readRDS("../Data/Liu_Wu_scVI_C4.rds")
```


```{r}
# Redo the analysis for this subset of data.
C4 <- FindNeighbors(C4, dims = 1:10)
C4 <- FindClusters(C4, resolution = 0.05) # 0.1 3 clusters
DimPlot(object = C4, reduction = "tsne",
                dims = c(2, 1), cells = NULL, cols = NULL,
                pt.size = NULL, group.by = NULL, 
                split.by = NULL, shape.by = NULL, order = NULL, 
                label = TRUE,  label.size = 4, repel = FALSE, 
                cells.highlight = NULL, cols.highlight = "#DE2D26", 
                sizes.highlight = 1, na.value = "grey50", 
                combine = TRUE, ncol = NULL)
```

```{r}
C4 <- FindClusters(C4, resolution = 0.1) # 0.1 3 clusters
DimPlot(object = C4, reduction = "tsne",
                dims = c(2, 1), cells = NULL, cols = NULL,
                pt.size = NULL, group.by = NULL, 
                split.by = NULL, shape.by = NULL, order = NULL, 
                label = TRUE,  label.size = 4, repel = FALSE, 
                cells.highlight = NULL, cols.highlight = "#DE2D26", 
                sizes.highlight = 1, na.value = "grey50", 
                combine = TRUE, ncol = NULL)
```


```{r}
C4 <- FindVariableFeatures(object = C4,
                          mean.function = ExpMean,
                          dispersion.function = LogVMR,
                          x.low.cutoff = 0.0125,
                          x.high.cutoff = 3,
                          y.cutoff = 0.5)
C4 <- ScaleData(object = C4)
C4 <- RunPCA(object = C4,
               features = C4@assays$wu_liu_scVI_imputation@var.features,
               npcs = 100,
               verbose = TRUE,
               set.seed = 42,
               ndims.print = 1:5,
               nfeatures.print = 5)
C4 <- RunTSNE(object = C4, 
                  reduction = "pca", 
                  tsne.method = "Rtsne",
                  dims = 1:75,
                  set.seed = 777)
C4 <- FindNeighbors(C4, dims = 1:10)
C4 <- FindClusters(C4, resolution = 0.1)
DimPlot(object = C4, reduction = "tsne",
                dims = c(2, 1), cells = NULL, cols = NULL,
                pt.size = NULL, group.by = NULL, 
                split.by = NULL, shape.by = NULL, order = NULL, 
                label = TRUE,  label.size = 4, repel = FALSE, 
                cells.highlight = NULL, cols.highlight = "#DE2D26", 
                sizes.highlight = 1, na.value = "grey50", 
                combine = TRUE, ncol = NULL)
```

```
Liu <- read.csv("lin_scRNAseq_sub.csv.gz", row.names = 1)
Wu <- read.csv("wu_scRNAseq_sub.csv.gz", row.names = 1)
```



```{r}
C4.data <- GetAssayData(C4, slot = "data")
C4.dist <- dist(t(as.matrix(C4.data)))
```

```{r}
saveRDS(C4.dist, file = "../Data/Euclidean_C4_Liu_Wu.rds")
```

```{r}
C4_cells <- C4@assays$wu_liu_scVI_imputation@data@Dimnames[[2]]
```


```{r}
Wu_orig <- readRDS("Wu_obj.RDS")
Liu_orig <- readRDS("Liu_obj.RDS")
```

```{r}
Wu_orig_C4 <- subset(x = Wu_orig, cells = C4_cells)
Liu_orig_C4 <- subset(x = Liu_orig, cells = C4_cells)
```

```{r}
Wu_orig_C4.data <- GetAssayData(Wu_orig_C4, slot = "data")
Wu_orig_C4.dist <- dist(t(as.matrix(Wu_orig_C4.data)))
saveRDS(Wu_orig_C4.dist, file = "Euclidean_C4_Wu_Orig.rds")
```

```{r}
Liu_orig_C4.data <- GetAssayData(Liu_orig_C4, slot = "data")
Liu_orig_C4.dist <- dist(t(as.matrix(Liu_orig_C4.data)))
saveRDS(Liu_orig_C4.dist, file = "Euclidean_C4_Liu_Orig.rds")
```


```{r}
C4.dist <- readRDS("Euclidean_C4_Liu_Wu.rds")
Wu_orig_C4.dist <- readRDS("Euclidean_C4_Wu_Orig.rds")
Liu_orig_C4.dist <- readRDS("Euclidean_C4_Liu_Orig.rds")
```


```{r}
C4.dist.matrix <- as.matrix(C4.dist)
Wu_orig_C4.dist.matrix <- as.matrix(Wu_orig_C4.dist)
Liu_orig_C4.dist.matrix <- as.matrix(Liu_orig_C4.dist)
```

```{r}
dim(C4.dist.matrix)
dim(Wu_orig_C4.dist.matrix)
dim(Liu_orig_C4.dist.matrix)
```

```{r}
Wu_C4.dist.matrix <- C4.dist.matrix[1:992, 1:992]
Liu_C4.dist.matrix <- C4.dist.matrix[993:1863, 993:1863]
```

```{r}
Liu_orig_C4.dist.matrix[1:4, 1:4]
Liu_C4.dist.matrix[1:4, 1:4]
```

```{r}
Wu_orig_C4.dist.matrix[1:4, 1:4]
Wu_C4.dist.matrix[1:4, 1:4]
```

```{r}
Wu_orig_C4.dist.matrix.scale <- Wu_orig_C4.dist.matrix / mean(rowMeans(Wu_orig_C4.dist.matrix)) 
# columnwise divide if divide by the vector. 
Wu_C4.dist.matrix.scale <- Wu_C4.dist.matrix / mean(rowMeans(Wu_C4.dist.matrix))
Wu_orig_C4.dist.matrix.scale[1:5, 1:5]
Wu_C4.dist.matrix.scale[1:5, 1:5]
```

```{r}
hist(Wu_orig_C4.dist.matrix.scale[1, ], breaks = 50)
hist(Wu_C4.dist.matrix.scale[1, ], breaks = 50)

hist(log(Wu_orig_C4.dist.matrix.scale[1, ]), breaks = 50)
hist(log(Wu_C4.dist.matrix.scale[1, ]), breaks = 50)
```

```{r}
Wu_orig_C4.dist.matrix.scale.log <- log(Wu_orig_C4.dist.matrix.scale)
Wu_C4.dist.matrix.scale.log <- log(Wu_C4.dist.matrix.scale)
Wu_orig_C4.dist.matrix.scale.log[1:5, 1:5]
Wu_C4.dist.matrix.scale.log[1:5, 1:5]
```


```{r}
t.test(Wu_orig_C4.dist.matrix.scale.log[1, -1], Wu_C4.dist.matrix.scale.log[1, -1], paired = T)
```
```{r}
wilcox.test(Wu_orig_C4.dist.matrix[1, ], Wu_C4.dist.matrix[1, ], paired = T)
```

```{r}
wilcox.test(Wu_orig_C4.dist.matrix.scale[1, ], Wu_C4.dist.matrix.scale[1, ], paired = T)
```

```{r}
wilcox.test(Wu_orig_C4.dist.matrix.scale.log[1, -1], Wu_C4.dist.matrix.scale.log[1, -1], paired = T)
```

```{r}
Liu_orig_C4.dist.matrix.scale <- Liu_orig_C4.dist.matrix / mean(rowMeans(Liu_orig_C4.dist.matrix)) 
Liu_C4.dist.matrix.scale <- Liu_C4.dist.matrix / mean(rowMeans(Liu_C4.dist.matrix))
Liu_orig_C4.dist.matrix.scale[1:5, 1:5]
Liu_C4.dist.matrix.scale[1:5, 1:5]

Liu_C4.matrix.scale <- rbind(Liu_orig_C4.dist.matrix.scale, Liu_C4.dist.matrix.scale)
```
```{r}
Liu_C4.matrix <- rbind(Liu_orig_C4.dist.matrix, Liu_C4.dist.matrix)
system.time(
  Liu_C4.WilcoxonSignedRank <- apply(Liu_C4.matrix, 2, function(X) {
  n <- length(X)
  X_orig <- X[1:(n/2)]
  X_Sim <- X[(n/2+1):n]
  wilcox.test(X_orig, X_Sim, paired = T)$p.value
})
)
plot(Liu_C4.WilcoxonSignedRank)
plot(p.adjust(Liu_C4.WilcoxonSignedRank))
```

```{r}
Wu_C4.matrix <- rbind(Wu_orig_C4.dist.matrix, Wu_C4.dist.matrix)

system.time(
  Wu_C4.WilcoxonSignedRank <- apply(Wu_C4.matrix, 2, function(X) {
  n <- length(X)
  X_orig <- X[1:(n/2)]
  X_Sim <- X[(n/2+1):n]
  wilcox.test(X_orig, X_Sim, paired = T)$p.value
})
)
plot(Wu_C4.WilcoxonSignedRank)
plot(p.adjust(Wu_C4.WilcoxonSignedRank))
```
```{r}
Liu_C4.matrix.scale <- rbind(Liu_orig_C4.dist.matrix.scale, Liu_C4.dist.matrix.scale)
system.time(
  Liu_C4.scale.WilcoxonSignedRank <- apply(Liu_C4.matrix.scale, 2, function(X) {
  n <- length(X)
  X_orig <- X[1:(n/2)]
  X_Sim <- X[(n/2+1):n]
  wilcox.test(X_orig, X_Sim, paired = T)$p.value
})
)

plot(Liu_C4.scale.WilcoxonSignedRank)
plot(p.adjust(Liu_C4.scale.WilcoxonSignedRank))
```

```{r}
Wu_C4.matrix.scale <- rbind(Wu_orig_C4.dist.matrix.scale, Wu_C4.dist.matrix.scale)

system.time(
  Wu_C4.scale.WilcoxonSignedRank <- apply(Wu_C4.matrix.scale, 2, function(X) {
  n <- length(X)
  X_orig <- X[1:(n/2)]
  X_Sim <- X[(n/2+1):n]
  wilcox.test(X_orig, X_Sim, paired = T)$p.value
})
)
plot(Wu_C4.scale.WilcoxonSignedRank)
plot(p.adjust(Wu_C4.scale.WilcoxonSignedRank))
```

```{r}
hist(Liu_C4.WilcoxonSignedRank, breaks = 50)
hist(Wu_C4.WilcoxonSignedRank, breaks = 50)
```

```{r}
Wu_C4.WilcoxonSignedRank.adjust <- p.adjust(Wu_C4.WilcoxonSignedRank)
Liu_C4.WilcoxonSignedRank.adjust <- p.adjust(Liu_C4.WilcoxonSignedRank)
```

```{r}
hist(Liu_C4.WilcoxonSignedRank.adjust, breaks = 50)
hist(Wu_C4.WilcoxonSignedRank.adjust, breaks = 50)
```


## Self written wilcoxon sign rank test. 
```{r}
Wu_C4.dist.matrix.diff <- Wu_orig_C4.dist.matrix - Wu_C4.dist.matrix
Liu_C4.dist.matrix.diff <- Liu_orig_C4.dist.matrix - Liu_C4.dist.matrix

Wu_C4.dist.matrix.diff.sign <- sign(Wu_C4.dist.matrix.diff)
Liu_C4.dist.matrix.diff.sign <- sign(Liu_C4.dist.matrix.diff)
```

```{r}
Wu_C4.dist.matrix.diff.abs <- abs(Wu_C4.dist.matrix.diff)
Liu_C4.dist.matrix.diff.abs <- abs(Liu_C4.dist.matrix.diff)
```

```{r}
X <- Wu_C4.dist.matrix.diff.abs[1, ]
sign <- Wu_C4.dist.matrix.diff.sign[1, ]
gg.wilcox.test <- function(X, sign) {
  X_nonzero <- X[X != 0]
  N <- length(X_nonzero)
  ranks <- rank(X, ties.method = "average")
  ranksigned <- ranks * sign
  W <- sum(ranksigned)
  sigma_W <- sqrt(N * (N + 1) * (2 * N + 1) / 6)
  Z <- W / sigma_W
  2 * (1 - pnorm(abs(Z)))
  #pwilcox(W, m = N, n = N)
}
gg.wilcox.test(X, sign)
```

```{r}
N <- nrow(Wu_C4.dist.matrix.diff.abs)
p_val <- rep(NA, N)
system.time(
  for(i in 1:N) {
   p_val[i] <- gg.wilcox.test(Wu_C4.dist.matrix.diff.abs[i, ], Wu_C4.dist.matrix.diff.sign[i, ])
  }
)
```
```{r}
plot(p_val)
#hist(p_val)
```

```{r}
Wu_orig_C4.dist.matrix.rank <- apply(Wu_orig_C4.dist.matrix, 2, rank)
Liu_orig_C4.dist.matrix.rank <- apply(Liu_orig_C4.dist.matrix, 2, rank)

Wu_C4.dist.matrix.rank <- apply(Wu_C4.dist.matrix, 2, rank)
Liu_C4.dist.matrix.rank <- apply(Liu_C4.dist.matrix, 2, rank)
```

```{r}
Wu_orig_C4.dist.matrix.rank[1:4, 1:4]
Liu_orig_C4.dist.matrix.rank[1:4, 1:4]
Wu_C4.dist.matrix.rank[1:4, 1:4]
Liu_C4.dist.matrix.rank[1:4, 1:4]
```




```{r}
Wu_C4.dist.rank.diff <- (Wu_orig_C4.dist.matrix.rank - Wu_C4.dist.matrix.rank)
Liu_C4.dist.rank.diff <- (Liu_orig_C4.dist.matrix.rank - Liu_C4.dist.matrix.rank)
Wu_C4.dist.rank.diff[1:4, 1:4]
Liu_C4.dist.rank.diff[1:4, 1:4]
```

```{r}
hist(Wu_C4.dist.rank.diff[1, ], breaks = 30)
hist(Liu_C4.dist.rank.diff[1, ], breaks = 30)
```

```{r}
Wu_C4.dist.rank.diff[1:3, 1:3]
Liu_C4.dist.rank.diff[1:3, 1:3]
```
```{r}
hist(Wu_C4.dist.rank.diff[, 1])
hist(log(Wu_C4.dist.rank.diff[, 1]))
```


```{r}
Wu_C4.dist.rank.diff.sum <- apply(Wu_C4.dist.rank.diff, 2, sum)
Liu_C4.dist.rank.diff.sum <- apply(Liu_C4.dist.rank.diff, 2, sum)
```


```{r}
head(Wu_C4.dist.rank.diff.sum)
head(Liu_C4.dist.rank.diff.sum)
```

```{r}
Liu_C4.WilcoxonSignedRank.log <- log10(Liu_C4.WilcoxonSignedRank)
Wu_C4.WilcoxonSignedRank.log <- log10(Wu_C4.WilcoxonSignedRank)
```

```{r}
Wu_C4.WilcoxonSignedRank.log[1:5]
```

```{r}
as.matrix(Liu_orig_C4.data)[1:4, 1:4]
Wu_orig_C4.data[1:4, 1:4]
C4.data[1:4, 1:4]
```
```{r}
Liu_orig_C4.data.cellMean <- colSums(as.matrix(Liu_orig_C4.data))
Wu_orig_C4.data.cellMean <- colSums(as.matrix(Wu_orig_C4.data))
C4.data.cellMean <- colSums(as.matrix(C4.data))
```

```{r}
Wu_orig_C4.data.cellMean[1:5]
C4.data.cellMean[1:5]
```
```{r}
plot(Wu_orig_C4.data.cellMean, -Wu_C4.WilcoxonSignedRank.log)
plot(Liu_orig_C4.data.cellMean, -Liu_C4.WilcoxonSignedRank.log)
```

```{r}
plot(log10(Wu_orig_C4.data.cellMean), -Wu_C4.WilcoxonSignedRank.log)
plot(log10(Liu_orig_C4.data.cellMean), -Liu_C4.WilcoxonSignedRank.log)
```
## Should see vocanol shape? 
